pub struct SmartHealthInfo {}
pub struct FwCommitInfo {}
pub struct TimestampChangeInfo {}
pub struct PorInfo {}
pub struct NvmHwErrorInfo {}
pub struct ChangeNamespaceInfo {}
pub struct FormatNvmStartInfo {}
pub struct FormatNvmCompleteInfo {}
pub struct SanitizeStartInfo {}
pub struct SanitizeCompleteInfo {}
pub struct SetFeatureInfo {}
pub struct TelementryLogCreatedInfo {}
pub struct ThermalExcursionInfo {}
pub struct VendorSpecifcInfo {}
pub struct TcgDefinedInfo {}
pub struct UnsupportedInfo {}
